-- =============================================================================
-- SCHEM FINAL SQL
-- Combined live schema scripts (merged in requested order)
-- =============================================================================
-- Generated by merging:
-- 1) live_schema_customer_ledger.sql
-- 2) live_schema_international_payable_group_payment_tables.sql
-- 3) live_schema_international_payable_payment_management.sql
-- 4) live_schema_international_payables_combined_payment.sql
-- 5) live_schema_international_payables_grouping.sql
-- 6) live_schema_international_payables_page_combined_payment.sql
-- 7) live_schema_opening_balance_receivable.sql
-- 8) live_schema_payable_group_payment_tables.sql
-- 9) live_schema_payable_payment_parts.sql
-- 10) live_schema_payables_grouping_and_combined_payment.sql
-- 11) live_schema_payables_page_combined_payment.sql
-- 12) live_schema_purchases_grouping.sql
-- =============================================================================

-- =============================================================================
-- BEGIN: live_schema_customer_ledger.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — Customer ledger + combined receivable payment linkage
-- =============================================================================
-- Purpose: align production with Laravel migrations for customer AR ledger:
--   • receivable_group_payments / receivable_group_payment_lines (FIFO group pay)
--   • customer_ledger_entries (per-customer statement lines: sale, payment, etc.)
--   • customer_ledger_entries.receivable_group_payment_id (legacy link column)
--   • customer_ledger_receivable_group_payments (junction: one ledger row ↔ group pay)
--
-- Prerequisites: `customers` exists (InnoDB recommended for FKs). `receivables` is
-- not referenced by FK here (lines use receivable_id without DB FK by design).
--
-- Safe to run multiple times. Run after backup. Deploy matching app code.
-- =============================================================================

SET @db := DATABASE();

-- ---------------------------------------------------------------------------
-- receivable_group_payments
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `receivable_group_payments` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `group_key` VARCHAR(512) NOT NULL,
    `payment_date` DATE NOT NULL,
    `amount` DECIMAL(10, 2) NOT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `receivable_group_payments_group_key_index` (`group_key`),
    KEY `receivable_group_payments_payment_date_index` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- receivable_group_payment_lines (no FK to receivables / ledger — app-enforced)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `receivable_group_payment_lines` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `receivable_group_payment_id` BIGINT UNSIGNED NOT NULL,
    `receivable_id` BIGINT UNSIGNED NOT NULL,
    `amount` DECIMAL(10, 2) NOT NULL,
    `customer_ledger_entry_id` INT UNSIGNED NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `rgpl_ar_group_pay_idx` (`receivable_group_payment_id`),
    KEY `rgpl_receivable_id_idx` (`receivable_id`),
    KEY `rgpl_cust_ledger_idx` (`customer_ledger_entry_id`),
    CONSTRAINT `rgpl_ar_group_pay_fk`
        FOREIGN KEY (`receivable_group_payment_id`) REFERENCES `receivable_group_payments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- customer_ledger_entries (base table; receivable_group_payment_id added below)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer_ledger_entries` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_id` INT UNSIGNED NOT NULL,
    `date` DATETIME NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    `reference` VARCHAR(100) NULL DEFAULT NULL,
    `debit` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    `credit` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    `source_type` VARCHAR(30) NULL DEFAULT NULL,
    `source_id` INT UNSIGNED NULL DEFAULT NULL,
    `notes` TEXT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `customer_ledger_entries_customer_id_index` (`customer_id`),
    KEY `customer_ledger_entries_date_index` (`date`),
    KEY `customer_ledger_entries_source_type_source_id_index` (`source_type`, `source_id`),
    CONSTRAINT `customer_ledger_entries_customer_id_foreign`
        FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- If CREATE failed earlier because customers was missing, fix that first; do not
-- strip the FK above without understanding your data.

-- ---------------------------------------------------------------------------
-- customer_ledger_entries.receivable_group_payment_id + index + FK
-- ---------------------------------------------------------------------------
SET @sql := (
    SELECT IF(
        EXISTS(
            SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'customer_ledger_entries'
              AND COLUMN_NAME = 'receivable_group_payment_id'
        ),
        'SELECT ''skip: customer_ledger_entries.receivable_group_payment_id exists'' AS _msg',
        'ALTER TABLE `customer_ledger_entries` ADD COLUMN `receivable_group_payment_id` BIGINT UNSIGNED NULL DEFAULT NULL AFTER `source_id`'
    )
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'customer_ledger_entries'
      AND INDEX_NAME = 'cle_ar_group_pay_idx'
);
SET @sql := IF(
    @idx_exists > 0,
    'SELECT ''skip: cle_ar_group_pay_idx exists'' AS _msg',
    'ALTER TABLE `customer_ledger_entries` ADD INDEX `cle_ar_group_pay_idx` (`receivable_group_payment_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @fk_exists := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'customer_ledger_entries'
      AND CONSTRAINT_TYPE = 'FOREIGN KEY' AND CONSTRAINT_NAME = 'cle_ar_group_pay_fk'
);
SET @sql := IF(
    @fk_exists > 0,
    'SELECT ''skip: cle_ar_group_pay_fk exists'' AS _msg',
    'ALTER TABLE `customer_ledger_entries` ADD CONSTRAINT `cle_ar_group_pay_fk` FOREIGN KEY (`receivable_group_payment_id`) REFERENCES `receivable_group_payments` (`id`) ON DELETE SET NULL'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- If the FK ALTER fails (e.g. customer_ledger_entries not InnoDB), add the column
-- and index only, then: ALTER TABLE customer_ledger_entries ENGINE=InnoDB;

-- ---------------------------------------------------------------------------
-- customer_ledger_receivable_group_payments (preferred link for merged statement rows)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer_ledger_receivable_group_payments` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_ledger_entry_id` INT UNSIGNED NOT NULL,
    `receivable_group_payment_id` BIGINT UNSIGNED NOT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `cl_rgp_ledger_unique` (`customer_ledger_entry_id`),
    KEY `cl_rgp_group_idx` (`receivable_group_payment_id`),
    CONSTRAINT `cl_rgp_ledger_fk` FOREIGN KEY (`customer_ledger_entry_id`) REFERENCES `customer_ledger_entries` (`id`) ON DELETE CASCADE,
    CONSTRAINT `cl_rgp_group_fk` FOREIGN KEY (`receivable_group_payment_id`) REFERENCES `receivable_group_payments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- Optional one-time backfill: copy legacy column into junction table (uncomment).
-- -----------------------------------------------------------------------------
-- INSERT INTO `customer_ledger_receivable_group_payments`
--   (`customer_ledger_entry_id`, `receivable_group_payment_id`, `created_at`, `updated_at`)
-- SELECT `id`, `receivable_group_payment_id`, NOW(), NOW()
-- FROM `customer_ledger_entries`
-- WHERE `receivable_group_payment_id` IS NOT NULL
--   AND NOT EXISTS (
--     SELECT 1 FROM `customer_ledger_receivable_group_payments` l
--     WHERE l.`customer_ledger_entry_id` = `customer_ledger_entries`.`id`
--   );

SELECT 'live_schema_customer_ledger.sql completed' AS result;
-- =============================================================================
-- END: live_schema_customer_ledger.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_international_payable_group_payment_tables.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — International payable combined-payment tables (idempotent)
-- =============================================================================
SET @db := DATABASE();

CREATE TABLE IF NOT EXISTS `international_payable_group_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_key` VARCHAR(512) NOT NULL,
  `payment_date` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `notes` VARCHAR(500) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `international_payable_group_payments_group_key_index` (`group_key`),
  KEY `international_payable_group_payments_payment_date_index` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `international_payable_group_payment_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `international_payable_group_payment_id` BIGINT UNSIGNED NOT NULL,
  `international_purchase_order_id` BIGINT UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `international_payable_payment_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ipgpl_order_idx` (`international_purchase_order_id`),
  KEY `ipgpl_payment_idx` (`international_payable_payment_id`),
  KEY `ipgpl_group_fk` (`international_payable_group_payment_id`),
  CONSTRAINT `ipgpl_group_fk`
    FOREIGN KEY (`international_payable_group_payment_id`) REFERENCES `international_payable_group_payments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Ensure indexes/FKs exist even if tables already existed
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_group_payments'
    AND INDEX_NAME = 'international_payable_group_payments_group_key_index'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: international_payable_group_payments_group_key_index exists'' AS _msg',
  'ALTER TABLE `international_payable_group_payments` ADD INDEX `international_payable_group_payments_group_key_index` (`group_key`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_group_payments'
    AND INDEX_NAME = 'international_payable_group_payments_payment_date_index'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: international_payable_group_payments_payment_date_index exists'' AS _msg',
  'ALTER TABLE `international_payable_group_payments` ADD INDEX `international_payable_group_payments_payment_date_index` (`payment_date`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_group_payment_lines'
    AND INDEX_NAME = 'ipgpl_order_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: ipgpl_order_idx exists'' AS _msg',
  'ALTER TABLE `international_payable_group_payment_lines` ADD INDEX `ipgpl_order_idx` (`international_purchase_order_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_group_payment_lines'
    AND INDEX_NAME = 'ipgpl_payment_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: ipgpl_payment_idx exists'' AS _msg',
  'ALTER TABLE `international_payable_group_payment_lines` ADD INDEX `ipgpl_payment_idx` (`international_payable_payment_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @fk_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_group_payment_lines'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND CONSTRAINT_NAME = 'ipgpl_group_fk'
);
SET @sql := IF(
  @fk_exists > 0,
  'SELECT ''skip: ipgpl_group_fk exists'' AS _msg',
  'ALTER TABLE `international_payable_group_payment_lines` ADD CONSTRAINT `ipgpl_group_fk` FOREIGN KEY (`international_payable_group_payment_id`) REFERENCES `international_payable_group_payments` (`id`) ON DELETE CASCADE'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @col_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND COLUMN_NAME = 'international_payable_group_payment_id'
);
SET @sql := IF(
  @col_exists > 0,
  'SELECT ''skip: international_payable_payments.international_payable_group_payment_id exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD COLUMN `international_payable_group_payment_id` BIGINT UNSIGNED NULL AFTER `international_purchase_order_id`'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND INDEX_NAME = 'int_pay_pay_group_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: int_pay_pay_group_idx exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD INDEX `int_pay_pay_group_idx` (`international_payable_group_payment_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @fk_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND CONSTRAINT_NAME = 'int_pay_pay_group_fk'
);
SET @sql := IF(
  @fk_exists > 0,
  'SELECT ''skip: int_pay_pay_group_fk exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD CONSTRAINT `int_pay_pay_group_fk` FOREIGN KEY (`international_payable_group_payment_id`) REFERENCES `international_payable_group_payments` (`id`) ON DELETE SET NULL'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_international_payable_group_payment_tables.sql completed' AS result;
-- =============================================================================
-- END: live_schema_international_payable_group_payment_tables.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_international_payable_payment_management.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — International payable payment management (idempotent)
-- =============================================================================
-- Purpose: ensure production schema supports recording international payable
-- payments by date and in multiple parts, including edit/delete workflows.
--
-- App changes for this feature are controller/routes/UI only; no new columns
-- were introduced. This script safely ensures required tables/indexes/FKs exist.
--
-- Safe to run multiple times. Backup first. Deploy matching app code.
-- =============================================================================

SET @db := DATABASE();

-- ---------------------------------------------------------------------------
-- 1) international_payable_payments (required)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `international_payable_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `international_purchase_order_id` BIGINT UNSIGNED NOT NULL,
  `payment_date` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `notes` VARCHAR(500) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `int_pay_pay_order_id_index` (`international_purchase_order_id`),
  KEY `int_pay_pay_payment_date_index` (`payment_date`),
  CONSTRAINT `int_pay_pay_order_id_foreign`
    FOREIGN KEY (`international_purchase_order_id`) REFERENCES `international_purchase_orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Add missing index on order id (if table existed without it)
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND INDEX_NAME = 'int_pay_pay_order_id_index'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: int_pay_pay_order_id_index exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD INDEX `int_pay_pay_order_id_index` (`international_purchase_order_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- Add missing index on payment_date
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND INDEX_NAME = 'int_pay_pay_payment_date_index'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: int_pay_pay_payment_date_index exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD INDEX `int_pay_pay_payment_date_index` (`payment_date`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- Add FK to order if missing (skip if FK already present)
SET @fk_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND CONSTRAINT_NAME = 'int_pay_pay_order_id_foreign'
);
SET @sql := IF(
  @fk_exists > 0,
  'SELECT ''skip: int_pay_pay_order_id_foreign exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD CONSTRAINT `int_pay_pay_order_id_foreign` FOREIGN KEY (`international_purchase_order_id`) REFERENCES `international_purchase_orders` (`id`) ON DELETE CASCADE'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- 2) supplier_ledger_entries source lookup index (performance for edit/delete)
-- ---------------------------------------------------------------------------
-- International payment update/delete uses:
--   WHERE source_type = ''international_payable_payment'' AND source_id = ?
-- Ensure a composite index exists (matches SupplierLedgerSchema defaults).
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'supplier_ledger_entries'
    AND INDEX_NAME = 'supplier_ledger_source_index'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: supplier_ledger_source_index exists'' AS _msg',
  'ALTER TABLE `supplier_ledger_entries` ADD INDEX `supplier_ledger_source_index` (`source_type`, `source_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_international_payable_payment_management.sql completed' AS result;
-- =============================================================================
-- END: live_schema_international_payable_payment_management.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_international_payables_combined_payment.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — International payables combined payment (idempotent)
-- =============================================================================
-- Purpose:
--   Support "record one combined payment for a vendor group" flow on
--   International Payables (FIFO allocation across open invoices).
--
-- Notes:
--   - No new columns/tables are required by this feature.
--   - This script adds safe indexes for production performance.
--   - Safe to run multiple times.
-- =============================================================================

SET @db := DATABASE();

-- ---------------------------------------------------------------------------
-- 1) international_purchase_orders: supplier/date/id traversal for FIFO
-- ---------------------------------------------------------------------------
-- Combined payment gathers vendor-group invoices oldest-first:
--   WHERE supplier_id = ? ORDER BY date, id
-- Add composite index if missing.
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_purchase_orders'
    AND INDEX_NAME = 'ipo_supplier_date_id_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: ipo_supplier_date_id_idx exists'' AS _msg',
  'ALTER TABLE `international_purchase_orders` ADD INDEX `ipo_supplier_date_id_idx` (`supplier_id`, `date`, `id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- 2) international_payable_payments: order/date/id scans
-- ---------------------------------------------------------------------------
-- Payment history and aggregate flows frequently use:
--   WHERE international_purchase_order_id = ?
--   ORDER BY payment_date DESC, id DESC
-- Add composite index if missing.
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND INDEX_NAME = 'int_pay_pay_order_date_id_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: int_pay_pay_order_date_id_idx exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD INDEX `int_pay_pay_order_date_id_idx` (`international_purchase_order_id`, `payment_date`, `id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- 3) supplier_ledger_entries: source/date lookup for audit trails
-- ---------------------------------------------------------------------------
-- Existing source index may already exist; this adds a date-extended variant
-- used by timeline-style reporting while filtering by source tuple.
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'supplier_ledger_entries'
    AND INDEX_NAME = 'supplier_ledger_source_date_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: supplier_ledger_source_date_idx exists'' AS _msg',
  'ALTER TABLE `supplier_ledger_entries` ADD INDEX `supplier_ledger_source_date_idx` (`source_type`, `source_id`, `date`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_international_payables_combined_payment.sql completed' AS result;
-- =============================================================================
-- END: live_schema_international_payables_combined_payment.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_international_payables_grouping.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — International payables grouping by vendor name (idempotent)
-- =============================================================================
-- Purpose: support grouped listing on International Payables index where
-- invoices with the same vendor name are merged into one row.
--
-- NOTE: This feature is primarily application logic (controller/view routing).
-- No new columns are required. This script adds safe indexes to keep grouping
-- and drill-down queries fast on production datasets.
--
-- Safe to run multiple times. Backup first.
-- =============================================================================

SET @db := DATABASE();

-- ---------------------------------------------------------------------------
-- suppliers.name lookup index (used for LOWER(TRIM(name)) matching flow)
-- ---------------------------------------------------------------------------
-- Existing schema usually has this index already. Add only if missing.
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'suppliers'
    AND INDEX_NAME = 'suppliers_name_index'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: suppliers_name_index exists'' AS _msg',
  'ALTER TABLE `suppliers` ADD INDEX `suppliers_name_index` (`name`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- international_purchase_orders.supplier_id index (group drill-down)
-- ---------------------------------------------------------------------------
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_purchase_orders'
    AND INDEX_NAME = 'international_purchase_orders_supplier_id_index'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: international_purchase_orders_supplier_id_index exists'' AS _msg',
  'ALTER TABLE `international_purchase_orders` ADD INDEX `international_purchase_orders_supplier_id_index` (`supplier_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- Optional composite index for listing order by date within supplier groups
-- ---------------------------------------------------------------------------
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_purchase_orders'
    AND INDEX_NAME = 'ipo_supplier_date_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: ipo_supplier_date_idx exists'' AS _msg',
  'ALTER TABLE `international_purchase_orders` ADD INDEX `ipo_supplier_date_idx` (`supplier_id`, `date`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_international_payables_grouping.sql completed' AS result;
-- =============================================================================
-- END: live_schema_international_payables_grouping.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_international_payables_page_combined_payment.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — International Payables page combined-payment tables (idempotent)
-- =============================================================================
-- Purpose:
--   Receivable-style grouped/combined payments on International Payables group page.
--   This is a standalone script for the International Payables page updates only.
-- =============================================================================

SET @db := DATABASE();

-- 1) international_payable_group_payments
CREATE TABLE IF NOT EXISTS `international_payable_group_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_key` VARCHAR(512) NOT NULL,
  `payment_date` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `notes` VARCHAR(500) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `international_payable_group_payments_group_key_index` (`group_key`),
  KEY `international_payable_group_payments_payment_date_index` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2) international_payable_group_payment_lines
CREATE TABLE IF NOT EXISTS `international_payable_group_payment_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `international_payable_group_payment_id` BIGINT UNSIGNED NOT NULL,
  `international_purchase_order_id` BIGINT UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `international_payable_payment_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ipgpl_order_idx` (`international_purchase_order_id`),
  KEY `ipgpl_payment_idx` (`international_payable_payment_id`),
  KEY `ipgpl_group_fk` (`international_payable_group_payment_id`),
  CONSTRAINT `ipgpl_group_fk`
    FOREIGN KEY (`international_payable_group_payment_id`) REFERENCES `international_payable_group_payments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3) international_payable_payments.international_payable_group_payment_id
SET @col_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND COLUMN_NAME = 'international_payable_group_payment_id'
);
SET @sql := IF(
  @col_exists > 0,
  'SELECT ''skip: international_payable_payments.international_payable_group_payment_id exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD COLUMN `international_payable_group_payment_id` BIGINT UNSIGNED NULL AFTER `international_purchase_order_id`'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND INDEX_NAME = 'int_pay_pay_group_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: int_pay_pay_group_idx exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD INDEX `int_pay_pay_group_idx` (`international_payable_group_payment_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @fk_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'international_payable_payments'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND CONSTRAINT_NAME = 'int_pay_pay_group_fk'
);
SET @sql := IF(
  @fk_exists > 0,
  'SELECT ''skip: int_pay_pay_group_fk exists'' AS _msg',
  'ALTER TABLE `international_payable_payments` ADD CONSTRAINT `int_pay_pay_group_fk` FOREIGN KEY (`international_payable_group_payment_id`) REFERENCES `international_payable_group_payments` (`id`) ON DELETE SET NULL'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_international_payables_page_combined_payment.sql completed' AS result;
-- =============================================================================
-- END: live_schema_international_payables_page_combined_payment.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_opening_balance_receivable.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — Opening balance → receivable row (idempotent MySQL / MariaDB)
-- =============================================================================
-- Purpose: allow a synthetic receivable per customer so the Receivables page
-- shows customers who have opening_balance but no sales.
--
-- Run after your main ERP schema is in place. Safe to run multiple times.
--
-- Laravel: deploy matching app code, then `php artisan migrate` OR run this
-- file manually if you do not use migrations on production.
-- =============================================================================

SET @db := DATABASE();

-- ---------------------------------------------------------------------------
-- customers.opening_balance (required for the feature; skip if already added)
-- ---------------------------------------------------------------------------
SET @sql := (
    SELECT IF(
        EXISTS(
            SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'opening_balance'
        ),
        'SELECT ''skip: customers.opening_balance exists'' AS _msg',
        'ALTER TABLE `customers` ADD COLUMN `opening_balance` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT ''AR opening; positive = owes'' AFTER `address`'
    )
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @sql := (
    SELECT IF(
        EXISTS(
            SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'opening_balance_date'
        ),
        'SELECT ''skip: customers.opening_balance_date exists'' AS _msg',
        'ALTER TABLE `customers` ADD COLUMN `opening_balance_date` DATE NULL COMMENT ''As-of for opening balance'' AFTER `opening_balance`'
    )
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- receivables.is_opening_balance + index (marks synthetic opening row)
-- ---------------------------------------------------------------------------
SET @sql := (
    SELECT IF(
        EXISTS(
            SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'receivables' AND COLUMN_NAME = 'is_opening_balance'
        ),
        'SELECT ''skip: receivables.is_opening_balance exists'' AS _msg',
        'ALTER TABLE `receivables` ADD COLUMN `is_opening_balance` TINYINT(1) NOT NULL DEFAULT 0 COMMENT ''1 = from customer opening balance'' AFTER `received`'
    )
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'receivables'
      AND INDEX_NAME = 'receivables_customer_code_is_opening_balance_index'
);
SET @sql := IF(
    @idx_exists > 0,
    'SELECT ''skip: opening index exists'' AS _msg',
    'ALTER TABLE `receivables` ADD INDEX `receivables_customer_code_is_opening_balance_index` (`customer_code`, `is_opening_balance`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_opening_balance_receivable.sql completed' AS result;
-- =============================================================================
-- END: live_schema_opening_balance_receivable.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_payable_group_payment_tables.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — Payable combined-payment tables (idempotent)
-- =============================================================================
-- Purpose:
--   Add payable-group payment tracking tables similar to receivable group
--   payments so one combined payment can be recorded/edited/removed by group.
-- =============================================================================

SET @db := DATABASE();

CREATE TABLE IF NOT EXISTS `payable_group_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_key` VARCHAR(512) NOT NULL,
  `payment_date` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `payable_group_payments_group_key_index` (`group_key`),
  KEY `payable_group_payments_payment_date_index` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payable_group_payment_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `payable_group_payment_id` BIGINT UNSIGNED NOT NULL,
  `payable_id` BIGINT UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `customer_ledger_entry_id` INT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pgpl_payable_id_idx` (`payable_id`),
  KEY `pgpl_cust_ledger_idx` (`customer_ledger_entry_id`),
  KEY `pgpl_ap_group_pay_fk` (`payable_group_payment_id`),
  CONSTRAINT `pgpl_ap_group_pay_fk`
    FOREIGN KEY (`payable_group_payment_id`) REFERENCES `payable_group_payments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customer_ledger_payable_group_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_ledger_entry_id` INT UNSIGNED NOT NULL,
  `payable_group_payment_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cle_pg_unique` (`customer_ledger_entry_id`, `payable_group_payment_id`),
  KEY `cle_pg_group_idx` (`payable_group_payment_id`),
  KEY `cle_pg_ledger_idx` (`customer_ledger_entry_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Ensure indexes exist even when tables already existed
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'payable_group_payments'
    AND INDEX_NAME = 'payable_group_payments_group_key_index'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: payable_group_payments_group_key_index exists'' AS _msg',
  'ALTER TABLE `payable_group_payments` ADD INDEX `payable_group_payments_group_key_index` (`group_key`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'payable_group_payments'
    AND INDEX_NAME = 'payable_group_payments_payment_date_index'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: payable_group_payments_payment_date_index exists'' AS _msg',
  'ALTER TABLE `payable_group_payments` ADD INDEX `payable_group_payments_payment_date_index` (`payment_date`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'payable_group_payment_lines'
    AND INDEX_NAME = 'pgpl_payable_id_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: pgpl_payable_id_idx exists'' AS _msg',
  'ALTER TABLE `payable_group_payment_lines` ADD INDEX `pgpl_payable_id_idx` (`payable_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'payable_group_payment_lines'
    AND INDEX_NAME = 'pgpl_cust_ledger_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: pgpl_cust_ledger_idx exists'' AS _msg',
  'ALTER TABLE `payable_group_payment_lines` ADD INDEX `pgpl_cust_ledger_idx` (`customer_ledger_entry_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @fk_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'payable_group_payment_lines'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND CONSTRAINT_NAME = 'pgpl_ap_group_pay_fk'
);
SET @sql := IF(
  @fk_exists > 0,
  'SELECT ''skip: pgpl_ap_group_pay_fk exists'' AS _msg',
  'ALTER TABLE `payable_group_payment_lines` ADD CONSTRAINT `pgpl_ap_group_pay_fk` FOREIGN KEY (`payable_group_payment_id`) REFERENCES `payable_group_payments` (`id`) ON DELETE CASCADE'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'customer_ledger_payable_group_payments'
    AND INDEX_NAME = 'cle_pg_group_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: cle_pg_group_idx exists'' AS _msg',
  'ALTER TABLE `customer_ledger_payable_group_payments` ADD INDEX `cle_pg_group_idx` (`payable_group_payment_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'customer_ledger_payable_group_payments'
    AND INDEX_NAME = 'cle_pg_ledger_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: cle_pg_ledger_idx exists'' AS _msg',
  'ALTER TABLE `customer_ledger_payable_group_payments` ADD INDEX `cle_pg_ledger_idx` (`customer_ledger_entry_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- Add payable_group_payment_id on customer_ledger_entries if missing
SET @col_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'customer_ledger_entries'
    AND COLUMN_NAME = 'payable_group_payment_id'
);
SET @sql := IF(
  @col_exists > 0,
  'SELECT ''skip: customer_ledger_entries.payable_group_payment_id exists'' AS _msg',
  'ALTER TABLE `customer_ledger_entries` ADD COLUMN `payable_group_payment_id` BIGINT UNSIGNED NULL AFTER `receivable_group_payment_id`'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'customer_ledger_entries'
    AND INDEX_NAME = 'cle_ap_group_pay_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: cle_ap_group_pay_idx exists'' AS _msg',
  'ALTER TABLE `customer_ledger_entries` ADD INDEX `cle_ap_group_pay_idx` (`payable_group_payment_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @fk_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'customer_ledger_entries'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND CONSTRAINT_NAME = 'cle_ap_group_pay_fk'
);
SET @sql := IF(
  @fk_exists > 0,
  'SELECT ''skip: cle_ap_group_pay_fk exists'' AS _msg',
  'ALTER TABLE `customer_ledger_entries` ADD CONSTRAINT `cle_ap_group_pay_fk` FOREIGN KEY (`payable_group_payment_id`) REFERENCES `payable_group_payments` (`id`) ON DELETE SET NULL'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_payable_group_payment_tables.sql completed' AS result;
-- =============================================================================
-- END: live_schema_payable_group_payment_tables.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_payable_payment_parts.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — Payable payment parts (idempotent MySQL / MariaDB)
-- =============================================================================
-- Purpose: support payable payment handling similar to receivables:
--   • record payments in parts by date
--   • edit/delete payable payment rows from ledger-backed entries
--
-- App code uses existing tables (`payables`, `customer_ledger_entries`), so this
-- script ensures required columns/indexes exist on production safely.
--
-- Safe to run multiple times. Backup first.
-- =============================================================================

SET @db := DATABASE();

-- ---------------------------------------------------------------------------
-- payables.received (total paid so far)
-- ---------------------------------------------------------------------------
SET @sql := (
    SELECT IF(
        EXISTS(
            SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'payables' AND COLUMN_NAME = 'received'
        ),
        'SELECT ''skip: payables.received exists'' AS _msg',
        'ALTER TABLE `payables` ADD COLUMN `received` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT ''Total amount paid so far'' AFTER `amount`'
    )
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- payables.received_date (latest payment date)
-- ---------------------------------------------------------------------------
SET @sql := (
    SELECT IF(
        EXISTS(
            SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'payables' AND COLUMN_NAME = 'received_date'
        ),
        'SELECT ''skip: payables.received_date exists'' AS _msg',
        'ALTER TABLE `payables` ADD COLUMN `received_date` DATE NULL AFTER `received`'
    )
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- customer_ledger_entries.source_type/source_id (required for payment_made rows)
-- ---------------------------------------------------------------------------
SET @sql := (
    SELECT IF(
        EXISTS(
            SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'customer_ledger_entries' AND COLUMN_NAME = 'source_type'
        ),
        'SELECT ''skip: customer_ledger_entries.source_type exists'' AS _msg',
        'ALTER TABLE `customer_ledger_entries` ADD COLUMN `source_type` VARCHAR(30) NULL COMMENT ''sale | payment_received | purchase | payment_made'' AFTER `credit`'
    )
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @sql := (
    SELECT IF(
        EXISTS(
            SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'customer_ledger_entries' AND COLUMN_NAME = 'source_id'
        ),
        'SELECT ''skip: customer_ledger_entries.source_id exists'' AS _msg',
        'ALTER TABLE `customer_ledger_entries` ADD COLUMN `source_id` INT UNSIGNED NULL COMMENT ''Originating model id'' AFTER `source_type`'
    )
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- Composite index used by payable payment sync/update/delete:
--   WHERE source_type = 'payment_made' AND source_id = ?
SET @idx_exists := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = @db
      AND TABLE_NAME = 'customer_ledger_entries'
      AND INDEX_NAME = 'idx_source'
);
SET @sql := IF(
    @idx_exists > 0,
    'SELECT ''skip: idx_source exists'' AS _msg',
    'ALTER TABLE `customer_ledger_entries` ADD INDEX `idx_source` (`source_type`, `source_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_payable_payment_parts.sql completed' AS result;
-- =============================================================================
-- END: live_schema_payable_payment_parts.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_payables_grouping_and_combined_payment.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — Payables grouping + combined payment allocation (idempotent)
-- =============================================================================
-- Purpose:
--   • Support grouped Payables list (same customer code/name in one row)
--   • Support combined payment allocation across grouped invoices (FIFO)
--
-- App changes are mostly controller/view logic; no new tables are required.
-- This script ensures production has efficient indexes used by those queries.
--
-- Safe to run multiple times. Backup first.
-- =============================================================================

SET @db := DATABASE();

-- ---------------------------------------------------------------------------
-- payables: grouping + ordering indexes
-- ---------------------------------------------------------------------------
-- Used by grouped Payables index and group drill-down:
--   - GROUP/lookup by customer_code (normalized)
--   - fallback GROUP/lookup by customer_name
--   - FIFO by date,id within a group

SET @idx_exists := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = @db
      AND TABLE_NAME = 'payables'
      AND INDEX_NAME = 'idx_customer_code'
);
SET @sql := IF(
    @idx_exists > 0,
    'SELECT ''skip: payables.idx_customer_code exists'' AS _msg',
    'ALTER TABLE `payables` ADD INDEX `idx_customer_code` (`customer_code`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = @db
      AND TABLE_NAME = 'payables'
      AND INDEX_NAME = 'idx_customer_name'
);
SET @sql := IF(
    @idx_exists > 0,
    'SELECT ''skip: payables.idx_customer_name exists'' AS _msg',
    'ALTER TABLE `payables` ADD INDEX `idx_customer_name` (`customer_name`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = @db
      AND TABLE_NAME = 'payables'
      AND INDEX_NAME = 'idx_date'
);
SET @sql := IF(
    @idx_exists > 0,
    'SELECT ''skip: payables.idx_date exists'' AS _msg',
    'ALTER TABLE `payables` ADD INDEX `idx_date` (`date`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- Composite index to help FIFO scans inside customer groups
SET @idx_exists := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = @db
      AND TABLE_NAME = 'payables'
      AND INDEX_NAME = 'payables_customer_code_date_id_idx'
);
SET @sql := IF(
    @idx_exists > 0,
    'SELECT ''skip: payables_customer_code_date_id_idx exists'' AS _msg',
    'ALTER TABLE `payables` ADD INDEX `payables_customer_code_date_id_idx` (`customer_code`, `date`, `id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- customer_ledger_entries: payment_made sync/update lookup index
-- ---------------------------------------------------------------------------
-- Used by payable sync/update/delete:
--   WHERE source_type = 'payment_made' AND source_id = ?
SET @idx_exists := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = @db
      AND TABLE_NAME = 'customer_ledger_entries'
      AND INDEX_NAME = 'idx_source'
);
SET @sql := IF(
    @idx_exists > 0,
    'SELECT ''skip: customer_ledger_entries.idx_source exists'' AS _msg',
    'ALTER TABLE `customer_ledger_entries` ADD INDEX `idx_source` (`source_type`, `source_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_payables_grouping_and_combined_payment.sql completed' AS result;
-- =============================================================================
-- END: live_schema_payables_grouping_and_combined_payment.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_payables_page_combined_payment.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — Payables page combined-payment tables (idempotent)
-- =============================================================================
-- Purpose:
--   Receivable-style grouped/combined payments on Payables group page.
--   This is a standalone script for the Payables page updates only.
-- =============================================================================

SET @db := DATABASE();

-- 1) payable_group_payments
CREATE TABLE IF NOT EXISTS `payable_group_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_key` VARCHAR(512) NOT NULL,
  `payment_date` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `payable_group_payments_group_key_index` (`group_key`),
  KEY `payable_group_payments_payment_date_index` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2) payable_group_payment_lines
CREATE TABLE IF NOT EXISTS `payable_group_payment_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `payable_group_payment_id` BIGINT UNSIGNED NOT NULL,
  `payable_id` BIGINT UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `customer_ledger_entry_id` INT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pgpl_payable_id_idx` (`payable_id`),
  KEY `pgpl_cust_ledger_idx` (`customer_ledger_entry_id`),
  KEY `pgpl_ap_group_pay_fk` (`payable_group_payment_id`),
  CONSTRAINT `pgpl_ap_group_pay_fk`
    FOREIGN KEY (`payable_group_payment_id`) REFERENCES `payable_group_payments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3) customer_ledger_payable_group_payments (link table)
CREATE TABLE IF NOT EXISTS `customer_ledger_payable_group_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_ledger_entry_id` INT UNSIGNED NOT NULL,
  `payable_group_payment_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cle_pg_unique` (`customer_ledger_entry_id`, `payable_group_payment_id`),
  KEY `cle_pg_group_idx` (`payable_group_payment_id`),
  KEY `cle_pg_ledger_idx` (`customer_ledger_entry_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4) customer_ledger_entries.payable_group_payment_id
SET @col_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'customer_ledger_entries'
    AND COLUMN_NAME = 'payable_group_payment_id'
);
SET @sql := IF(
  @col_exists > 0,
  'SELECT ''skip: customer_ledger_entries.payable_group_payment_id exists'' AS _msg',
  'ALTER TABLE `customer_ledger_entries` ADD COLUMN `payable_group_payment_id` BIGINT UNSIGNED NULL AFTER `receivable_group_payment_id`'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'customer_ledger_entries'
    AND INDEX_NAME = 'cle_ap_group_pay_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: cle_ap_group_pay_idx exists'' AS _msg',
  'ALTER TABLE `customer_ledger_entries` ADD INDEX `cle_ap_group_pay_idx` (`payable_group_payment_id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SET @fk_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'customer_ledger_entries'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY'
    AND CONSTRAINT_NAME = 'cle_ap_group_pay_fk'
);
SET @sql := IF(
  @fk_exists > 0,
  'SELECT ''skip: cle_ap_group_pay_fk exists'' AS _msg',
  'ALTER TABLE `customer_ledger_entries` ADD CONSTRAINT `cle_ap_group_pay_fk` FOREIGN KEY (`payable_group_payment_id`) REFERENCES `payable_group_payments` (`id`) ON DELETE SET NULL'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_payables_page_combined_payment.sql completed' AS result;
-- =============================================================================
-- END: live_schema_payables_page_combined_payment.sql
-- =============================================================================


-- =============================================================================
-- BEGIN: live_schema_purchases_grouping.sql
-- =============================================================================
-- =============================================================================
-- LIVE SITE — Purchases grouping by customer (idempotent MySQL / MariaDB)
-- =============================================================================
-- Purpose:
--   • Support grouped Purchases index (same customer code/name shown as one row)
--   • Support grouped Purchases detail page lookups by code/name
--
-- App change is mainly controller/view logic. No new tables are required.
-- This script ensures production has the indexes used by grouped queries.
--
-- Safe to run multiple times. Backup first.
-- =============================================================================

SET @db := DATABASE();

-- ---------------------------------------------------------------------------
-- purchases.customer_code (primary grouping key when present)
-- ---------------------------------------------------------------------------
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'purchases'
    AND INDEX_NAME = 'idx_customer_code'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: purchases.idx_customer_code exists'' AS _msg',
  'ALTER TABLE `purchases` ADD INDEX `idx_customer_code` (`customer_code`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- purchases.customer_name (fallback grouping key when code is missing)
-- ---------------------------------------------------------------------------
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'purchases'
    AND INDEX_NAME = 'idx_customer_name'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: purchases.idx_customer_name exists'' AS _msg',
  'ALTER TABLE `purchases` ADD INDEX `idx_customer_name` (`customer_name`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- purchases.date (latest invoice ordering in grouped views)
-- ---------------------------------------------------------------------------
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'purchases'
    AND INDEX_NAME = 'idx_date'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: purchases.idx_date exists'' AS _msg',
  'ALTER TABLE `purchases` ADD INDEX `idx_date` (`date`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

-- ---------------------------------------------------------------------------
-- Composite index for grouped drill-down and sorting
-- ---------------------------------------------------------------------------
SET @idx_exists := (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = @db
    AND TABLE_NAME = 'purchases'
    AND INDEX_NAME = 'purchases_customer_code_date_id_idx'
);
SET @sql := IF(
  @idx_exists > 0,
  'SELECT ''skip: purchases_customer_code_date_id_idx exists'' AS _msg',
  'ALTER TABLE `purchases` ADD INDEX `purchases_customer_code_date_id_idx` (`customer_code`, `date`, `id`)'
);
PREPARE _stmt FROM @sql;
EXECUTE _stmt;
DEALLOCATE PREPARE _stmt;

SELECT 'live_schema_purchases_grouping.sql completed' AS result;
-- =============================================================================
-- END: live_schema_purchases_grouping.sql
-- =============================================================================
